### ISSUE TITLE
WHEN will the code come?

### ISSUE THREAD

**Issue by LinghaoChan** [zengyi-li/NMCE-release#1]
I'm very confused why this empty repo can get 13 stars? I hope that the authors will make the code public!

**Comment by zengyi-li** [comment]
Hi, Thanks for your interest in our work. Sorry for the delay, the code has been under review in FAIR, which took longer than expected. It has just been uploaded, hope you find it helpful.

**Comment by LinghaoChan** [comment]
> 

Tanks a lot!
