### ISSUE TITLE
MNIST clustering

### ISSUE THREAD

**Issue by jsvir** [zengyi-li/NMCE-release#2]
Could you please share your clustering accuracy on MNIST dataset?

**Comment by boltzmann-Li** [comment]
Hi, 

The success of self-supervised learning rely on finding the right data-augmentation for the specific type of dataset under consideration. The most well studied augmentation is for image classifications (CIFAR, Imagenet, etc). In this work I also manually found the suitable augmentations for the COIL-20 and COIL-100 dataset. In the case of MNIST, standard image data augmentation do not work well, so you may need to hand tune your own augmentation, which I do not recommend. If you have limited compute resources, I recommend trying Fashion-MNIST, which has the same size as MNIST. In early stage of this project I tuned the augmentation for Fashion-MNIST, and it's still in the codebase, called 'fashionmnist'. You can consider trying this. If I remember correctly, it can reach ~79% cluster accuracy on the training set.

**Comment by zengyi-li** [comment]
Hi,

The success of self-supervised learning rely on finding the right data-augmentation for the specific type of dataset under consideration. The most well studied augmentation is for image classifications (CIFAR, Imagenet, etc). In this work I also manually found the suitable augmentations for the COIL-20 and COIL-100 dataset. In the case of MNIST, standard image data augmentation do not work well, so you may need to hand tune your own augmentation, which I do not recommend. If you have limited compute resources, I recommend trying Fashion-MNIST, which has the same size as MNIST. In early stage of this project I tuned the augmentation for Fashion-MNIST, and it's still in the codebase, called 'fashionmnist'. You can consider trying this. If I remember correctly, it can reach ~79% cluster accuracy on the training set.

**Comment by jsvir** [comment]
Thanks!
